version: '3'
services:
    node:
        build: ./docker/node
        image: admin-app-node
        volumes:
            - ./:/app
        entrypoint: ['tail', '-f', '/dev/null']
    app:
        image: admin-app-node
        depends_on:
            - node
        restart: on-failure
        volumes:
            - ./:/app
        ports:
            - '8080:8080'
        entrypoint: ['npm', 'run', 'dev']